### ISSUE TITLE
Illegal character ^ Error

### ISSUE THREAD

**Issue by instacyber** [8u1a/plyara#10]
When parsing valid YARA rules containing the XOR operator (^) in the condition, t_error is raised in interp.py. It appears the error can be solved by adding the character to the t_ignore variable, but I wanted to raise this as an issue rather than committing a fix as I don't know if this will impact other things.

**Comment by Tigzy** [comment]
Hey, same goes with '%' character

**Comment by Tigzy** [comment]
Same with '?' character

**Comment by Tigzy** [comment]
Another parsing issue with double backslash: 
`$s1` = `"\"\\\\\\\""`

**Comment by utkonos** [comment]
@Tigzy your double backslash issue is moved over to here:
https://github.com/plyara/plyara/issues/46
