### ISSUE TITLE
Space after comments "// " causes error

### ISSUE THREAD

**Issue by butlerallenj** [8u1a/plyara#12]
Spaces immediately after comment delimiters causes an error:

Example: 
`$s = /test/ // A test`
Result:
`unknown text at 'A' ; token of type 'ID'`

**EDIT**
This appears to only occur for regex strings with appended comments. Fixed example above and example in comment below

**Comment by butlerallenj** [comment]
To note the error occurs due to the space immediately after the comment delimiters. This works fine: `$s = /test/ //A test`

**Comment by utkonos** [comment]
This and other fixes are in the new project:
https://github.com/plyara/plyara
