### ISSUE TITLE
First run generating the parsetab.py file by ply causes warnings

### ISSUE THREAD

**Issue by 0x3a** [8u1a/plyara#15]
I noticed the generation of the `parsetab.py` file for the `ply` library is never done in the installation. This would cause first time usage (and any unprivileged usage after that) to cause warnings at runtime like: `WARNING: Couldn't create 'plyara.parsetab'. [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/plyara/parsetab.py'`

A solution would be to add a `test_suite` to the `setup.py` file per documentation here: http://setuptools.readthedocs.io/en/latest/setuptools.html

This would initiate the generation of the `parsetab.py` file at installation which would have permissions to write the file in the module installation directory.

**Comment by utkonos** [comment]
This and other fixes are in the new project:
https://github.com/plyara/plyara
