### ISSUE TITLE
Bug in BYTESTRING token regex

### ISSUE THREAD

**Issue by fission1110** [8u1a/plyara#16]
https://github.com/8u1a/plyara/blob/master/plyara/interp.py#L316

The BYTESTRING regex is currently
` r'\{[\|\(\)\[\]\-\?a-fA-f0-9\s]+\}'`

I'm fairly certain it's supposed to be
` r'\{[\|\(\)\[\]\-\?a-fA-F0-9\s]+\}'`

The second F is meant to be capitalized. Currently the regex is too inclusive and will miss errors where the hex contains some invalid characters.

**Comment by utkonos** [comment]
This and other fixes are in the new project:
https://github.com/plyara/plyara
