### ISSUE TITLE
Error: unknown text at '+' ; token of type 'PLUS'

### ISSUE THREAD

**Issue by Neo23x0** [8u1a/plyara#22]
I am using plyara in a script and get the following error.

```
Traceback (most recent call last):
  File "rule-export.py", line 19, in <module>
    rulesDict = interp.parseString(open(args.f).read(), isPrintDebug=False)
  File "/Library/Python/2.7/site-packages/plyara/interp.py", line 151, in parseString
    parser.parse(inputString)
  File "/Library/Python/2.7/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Library/Python/2.7/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Library/Python/2.7/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Library/Python/2.7/site-packages/plyara/interp.py", line 574, in p_error
    raise TypeError("unknown text at %r ; token of type %r" % (p.value, p.type))
TypeError: unknown text at '+' ; token of type 'PLUS'
```

The rule that causes the error is this one:
```
rule koadic_enum_users {
   meta:
      description = "Detects Koadic component"
      author = "Florian Roth"
      reference = "https://github.com/zerosum0x0/koadic"
      date = "2017-07-31"
      hash1 = "69b03e425c37ff2526d79aed8eccf671e8e51d5b9832ae3e870718b0342890b9"
   strings:
      $x1 = "Koadic.work.report(\"No interactive users found.\")" fullword ascii
      $x2 = "var sessions = wmi.ExecQuery(\"Select * from Win32_LogonSession Where LogonType = 2 OR LogonType = 10\");" fullword ascii
      $x3 = "var wmi = GetObject(\"winmgmts:{impersonationLevel=impersonate}!\\\\\\\\\" + computer + \"\\\\root\\\\cimv2\");" fullword ascii
      $x4 = "query += \"Associators of {Win32_LogonSession.LogonId=\" + session.LogonId;" fullword ascii
      $s1 = "info += session.LogonType + \"\\n\";" fullword ascii
      $s2 = "for (var f = new Enumerator(users); !f.atEnd(); f.moveNext())" fullword ascii
      $s3 = "info += session.Description + \"\\n\";" fullword ascii
   condition:
      ( uint16(0) == 0x7274 and filesize < 5KB and 1 of ($x*) ) or
      ( 2 of them )
}
```

**Comment by Taskr** [comment]
This happens due to \\\\\\\\\\\\\\\\\\\" in $x3. Currently the string is being parsed using:

    def t_STRING(t):
      #r'".+?"(?<![^\\]\\")'
      r'".*?"(?<![^\\]\\")(?<![^\\][\\]{3}")(?<![^\\][\\]{5}")'
      t.value = t.value
      return t

which will only account for a limited amount of consecutive \\\\ patterns before the " and prematurely terminate the string. This limitation can be overcome by using lexing state instead.

    states = (
        ('STRING','exclusive'),
    )

    def t_begin_STRING(t):
        r'"'
        t.lexer.escape = 0
        t.lexer.string_start = t.lexer.lexpos - 1
        t.lexer.begin('STRING')

    def t_STRING_value(t):
        r'.'
        if t.lexer.escape == 0 and t.value == '"':
            t.type = "STRING"
            t.value = t.lexer.lexdata[t.lexer.string_start : t.lexer.lexpos]
            t.lexer.begin('INITIAL')
            return t

        if t.value == '\\' or t.lexer.escape == 1:
            t.lexer.escape ^= 1            

    t_STRING_ignore = ' \t\n'
 
    def t_STRING_error(t):
        raise TypeError("Illegal character " + t.value[0] + " at line " + str(t.lexer.lineno))
        t.lexer.skip(1)

**Comment by beberlacrapule** [comment]
See my pull request for '\\' issue:
https://github.com/8u1a/plyara/pull/13/commits/bedd9c5ce5de49a18edbd13458905f9d07da9729

**Comment by beberlacrapule** [comment]
Did you try to fix this ?
I have the same problem with HYPHEN char.
It doesn't appear to be an issue with backslashes

EDIT: Finally this is

**Comment by Taskr** [comment]
@beberlacrapule is the rule you are having the HYPHEN char issue with available?

**Comment by beberlacrapule** [comment]
The rule is:

```
rule DomainScanV1_0 {
      meta:
      description = "Auto-generated rule on file DomainScanV1_0.exe"
      author = "yarGen Yara Rule Generator by Florian Roth"
      hash = "aefcd73b802e1c2bdc9b2ef206a4f24e"
   strings:
      $s0 = "dIJMuX$aO-EV"
      $s1 = "XELUxP\"-\\"
      $s2 = "KaR\"U'}-M,."
      $s3 = "V.)\\ZDxpLSav"
      $s4 = "Decompress error"
      $s5 = "Can't load library"
      $s6 = "Can't load function"
      $s7 = "com0tl32:.d"
   condition:
      all of them
}
```

Bug appears on $s1 because of the `\"` in middle of the string. But I'm using the fix from my pull request above.

**Comment by Taskr** [comment]
I tried out your fix. It seems to be working with the rule you provided.

**Comment by beberlacrapule** [comment]
Really ?
I got the following error with my fix:
`TypeError: unknown text at '-' ; token of type 'HYPHEN'`
because of the `$s1 = "XELUxP\"-\\"` string. It's because of the escaped `"` in the string.

**Comment by beberlacrapule** [comment]
@Neo23x0 Which plyara release are you using ?

**Comment by utkonos** [comment]
This and other fixes are in the project here:
https://github.com/plyara/plyara
