### ISSUE TITLE
TypeError: unknown text at '/' ; token of type 'FORWARDSLASH'

### ISSUE THREAD

**Issue by juanandresgs** [8u1a/plyara#23]
Is this because of comments? Or am I missing something?

**Comment by juanandresgs** [comment]
On that note, it's essential to get a line number of the file being parsed to resolve issues. Basically impossible to debug a big consolidated rule file.

**Comment by utkonos** [comment]
This and many more fixes are included in the new project here:
https://github.com/plyara/plyara
